p8105\_hw2\_zw2541
================
Zixu\_Wang
9/30/2018

Problem 1
=========

Read and clean the data
-----------------------

``` r
transit_data = read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>% 
  janitor::clean_names() %>% 
  select(line, station_name, station_latitude, station_longitude, starts_with("route"), entry, vending, entrance_type, ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
transit_data
```

    ## # A tibble: 1,868 x 19
    ##    line  station_name station_latitude station_longitu… route1 route2
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr> 
    ##  1 4 Av… 25th St                  40.7            -74.0 R      <NA>  
    ##  2 4 Av… 25th St                  40.7            -74.0 R      <NA>  
    ##  3 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  4 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  5 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  6 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  7 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  8 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  9 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ## 10 4 Av… 53rd St                  40.6            -74.0 R      <NA>  
    ## # ... with 1,858 more rows, and 13 more variables: route3 <chr>,
    ## #   route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>, route8 <int>,
    ## #   route9 <int>, route10 <int>, route11 <int>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

This dataset contains such variables: "line", "station name", "station latitude", "stantion longitude", "route1" to "route11", "entry", "vending", "entrance type" and "ADA compliance".

My data cleaning step:

-   Import the dataset
-   Clean the names
-   Select the variables I'm interested in
-   Use the ifelse function to convert the entry variable from character to a logical variable

This dataset contains 1868 rows and 19 columns. And these data are not tidy.

Question 1
----------

How many distinct stations are there?

``` r
distinct_stations = distinct(transit_data, station_name, line, .keep_all = T) 
nrow(distinct_stations)
```

    ## [1] 465

There are 465 distinct stations.

Question 2
----------

How many stations are ADA compliant?

``` r
distinct_stations %>% 
  filter(ada == T) %>% 
  nrow()
```

    ## [1] 84

84 stations are ADA compliant.

Question 3
----------

What proportion of station entrances / exits without vending allow entrance?

If we only count the distinct stations, the propotion of station entrances / exits without vending allow entrance is

``` r
distinct_stations %>% 
  filter(vending == "NO", entry == "TRUE") %>% 
  nrow() / nrow(filter(transit_data, vending == "NO"))
```

    ## [1] 0.0273224

If we count all of the stations (different entrances of the same unique station as difference stations), the propotion of station entrances / exits without vending allow entrance is

``` r
transit_data %>% 
  filter(vending == "NO", entry == "TRUE") %>% 
  nrow() / nrow(filter(transit_data, vending == "NO"))
```

    ## [1] 0.3770492

Reformat data
-------------

``` r
reform_transit_data = transit_data %>% 
  gather(key = route_number, value = route_name, route1:route11) 
reform_transit_data
```

    ## # A tibble: 20,548 x 10
    ##    line  station_name station_latitude station_longitu… entry vending
    ##    <chr> <chr>                   <dbl>            <dbl> <lgl> <chr>  
    ##  1 4 Av… 25th St                  40.7            -74.0 TRUE  YES    
    ##  2 4 Av… 25th St                  40.7            -74.0 TRUE  YES    
    ##  3 4 Av… 36th St                  40.7            -74.0 TRUE  YES    
    ##  4 4 Av… 36th St                  40.7            -74.0 TRUE  YES    
    ##  5 4 Av… 36th St                  40.7            -74.0 TRUE  YES    
    ##  6 4 Av… 45th St                  40.6            -74.0 TRUE  YES    
    ##  7 4 Av… 45th St                  40.6            -74.0 TRUE  YES    
    ##  8 4 Av… 45th St                  40.6            -74.0 TRUE  YES    
    ##  9 4 Av… 45th St                  40.6            -74.0 TRUE  YES    
    ## 10 4 Av… 53rd St                  40.6            -74.0 TRUE  YES    
    ## # ... with 20,538 more rows, and 4 more variables: entrance_type <chr>,
    ## #   ada <lgl>, route_number <chr>, route_name <chr>

``` r
reform_distinct_stations = distinct_stations %>% 
  gather(key = route_number, value = route_name, route1:route11)
reform_distinct_stations
```

    ## # A tibble: 5,115 x 10
    ##    line  station_name station_latitude station_longitu… entry vending
    ##    <chr> <chr>                   <dbl>            <dbl> <lgl> <chr>  
    ##  1 4 Av… 25th St                  40.7            -74.0 TRUE  YES    
    ##  2 4 Av… 36th St                  40.7            -74.0 TRUE  YES    
    ##  3 4 Av… 45th St                  40.6            -74.0 TRUE  YES    
    ##  4 4 Av… 53rd St                  40.6            -74.0 TRUE  YES    
    ##  5 4 Av… 59th St                  40.6            -74.0 TRUE  YES    
    ##  6 4 Av… 77th St                  40.6            -74.0 TRUE  YES    
    ##  7 4 Av… 86th St                  40.6            -74.0 TRUE  YES    
    ##  8 4 Av… 95th St                  40.6            -74.0 TRUE  YES    
    ##  9 4 Av… 9th St                   40.7            -74.0 TRUE  YES    
    ## 10 4 Av… Atlantic Av…             40.7            -74.0 TRUE  YES    
    ## # ... with 5,105 more rows, and 4 more variables: entrance_type <chr>,
    ## #   ada <lgl>, route_number <chr>, route_name <chr>

-   How many distinct stations serve the A train?

``` r
reform_distinct_stations %>% 
  filter(route_name == "A") %>% 
  nrow()
```

    ## [1] 60

Therefore, 60 distinct stations serve the A train.

-   Of the stations that serve the A train, how many are ADA compliant?

``` r
reform_distinct_stations %>% 
  filter(route_name == "A", ada == "TRUE") %>% 
  nrow()
```

    ## [1] 17

Therefore, 17 of the stations that serve the A train are ADA compliant.

Problem 2
=========

Read and clean the data
-----------------------

-   Read and clean the Mr. Trash Wheel sheet.

``` r
Wheel_data = read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 1, range = "A2:N258") %>% 
  janitor::clean_names() %>%
  filter(!is.na(dumpster)) %>% 
  mutate(sports_balls = as.integer(round(sports_balls, 0)))
```

-   Read and clean precipitation data for 2016.

``` r
precip_2016 = read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 4, range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(total)) %>% 
  mutate(year = "2016")
```

-   Read and clean precipitation data for 2017

``` r
precip_2017 = read_excel("./data/HealthyHarborWaterWheelTotals2017-9-26.xlsx", sheet = 3, range = "A2:B14") %>% 
  janitor::clean_names() %>% 
  filter(!is.na(total)) %>% 
  mutate(year = "2017")
```

-   Combine datasets and convert month to a character variable

``` r
precip_data = bind_rows(precip_2016, precip_2017) %>% 
  mutate(month = month.name[month]) %>% 
  select(year, everything())
precip_data
```

    ## # A tibble: 20 x 3
    ##    year  month     total
    ##    <chr> <chr>     <dbl>
    ##  1 2016  January    3.23
    ##  2 2016  February   5.32
    ##  3 2016  March      2.24
    ##  4 2016  April      1.78
    ##  5 2016  May        5.19
    ##  6 2016  June       3.2 
    ##  7 2016  July       6.09
    ##  8 2016  August     3.96
    ##  9 2016  September  4.53
    ## 10 2016  October    0.62
    ## 11 2016  November   1.47
    ## 12 2016  December   2.32
    ## 13 2017  January    2.34
    ## 14 2017  February   1.46
    ## 15 2017  March      3.57
    ## 16 2017  April      3.99
    ## 17 2017  May        5.64
    ## 18 2017  June       1.4 
    ## 19 2017  July       7.09
    ## 20 2017  August     4.44
